/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#002113',
        'on-error': '#690005',
        'secondary-fixed': '#6ffbbe',
        'secondary': '#4edea3',
        'surface-tint': '#89ceff',
        'primary-fixed-dim': '#89ceff',
        'outline': '#88929b',
        'inverse-on-surface': '#2d3038',
        'surface-container-high': '#272a32',
        'surface': '#10131a',
        'error': '#ffb4ab',
        'surface-container-low': '#191b23',
        'on-primary-fixed': '#001e2f',
        'secondary-container': '#00a572',
        'on-primary-container': '#003751',
        'on-tertiary-fixed-variant': '#930013',
        'on-error-container': '#ffdad6',
        'primary-container': '#0ea5e9',
        'on-primary-fixed-variant': '#004c6e',
        'tertiary-fixed': '#ffdad7',
        'primary': '#89ceff',
        'background': '#10131a',
        'surface-dim': '#10131a',
        'on-tertiary-container': '#6e000c',
        'inverse-surface': '#e1e2ec',
        'surface-bright': '#363941',
        'tertiary-container': '#ff6c66',
        'on-surface': '#e1e2ec',
        'inverse-primary': '#006591',
        'on-primary': '#00344d',
        'surface-container': '#1d1f27',
        'on-secondary': '#003824',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-secondary-fixed-variant': '#005236',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#4edea3',
        'outline-variant': '#3e4850',
        'on-background': '#e1e2ec',
        'surface-container-lowest': '#0b0e15',
        'on-tertiary': '#68000a',
        'primary-fixed': '#c9e6ff',
        'surface-variant': '#32353d',
        'surface-container-highest': '#32353d',
        'on-tertiary-fixed': '#410004',
        'on-secondary-container': '#00311f',
        'on-surface-variant': '#bec8d2',
        'tertiary': '#ffb3ad',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
